### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fernando-deka** [gjoliver/DreamBoothOnRay#1]
Hi!

I am trying to scale a Dreambooth training using ray with your script, however, there are some issues that I would like to discuss.
First, I cannot modify the batch size from 1, if I change it to 2, here is the error:

> File "train.py", line 149, in train_fn
    latents = vae.encode(batch["images"]).latent_dist.sample() * 0.18215
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/diffusers/models/vae.py", line 566, in encode
    h = self.encoder(x)
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/diffusers/models/vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/ray-sample/ray/python/ray/air/examples/dreambooth/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 2, 3, 512, 512]

Second, why do you split the model between 2 GPUs, I am using the same g5.12xlarge instances and I am able to load everything on 1 GPU.
Third, performance, I am seeing a huge performance impact when I run it between different nodes, here are some results:

1 worker 1 instance 1 GPU -> 1.8 it/s
4 worker 1 instance 4 GPU -> 3.5 it/s
2 worker 2 instances 2 GPU -> 0.5 it/s

From my debugging, I see that loss.backward() is taking 9 seconds to complete when I run the 2 instance configuration, with 4 workers 1 instance it takes 0.3 seconds and with 1 worker it is negligible.

Also when running across instances, internet usage spikes on those instances to over 500 MB/s up and down.

What could be the root issue of this extremely poor performance?

Thank you!!

**Comment by gjoliver** [comment]
1. Thanks for the issue. I can look into the error. probably some batch format issue.
2. Back then, fine-tuning would OOM if I only had 1 GPU. I don't know what changed on the huggingface side, maybe they made their models more efficient or something.
but it's nice if you can get tunning work on just 1 GPU. your batch size will likely to be limited though, if there is only 1 GPU.
3. How did you make it work for multiple instances? This script should only work for multiple GPUs on a single instance. Very curious here. Overall, 3 it/s should be good enough right? For DreamBooth, you usually only need to run 2, 3 hundred iterations.

**Comment by fernando-deka** [comment]
Hey, thanks for your reply.

I am using the code from the ray official repository: https://github.com/ray-project/ray/tree/master/python/ray/air/examples/dreambooth
It seems that the code there is your code + some slight modifications to make it run across multiple instances, that is how I made it work.

I am running the script with the base model of runwayml/stable-diffusion-v1-5 and is only using 15/24 GRAM.
Why did you choose to use CompVis/stable-diffusion-v1-4 instead?

Actually performance does matter to me, I need to fine tune stable diffusion with 30k images of multiple different concepts and I need to scale this as much as possible, otherwise I am stuck with training times of over 2-3 weeks.

Thank you for your time!

**Comment by gjoliver** [comment]
Ah I see. Yeah that makes sense.
That’s a better example!
I don’t know how much you can speed things up vertically (per sample batch latency may be hard to improve).
But you can certainly scale things up horizontally (much bigger) sample batches, using more instances.
If you do DDP the bandwidth between all these GPUs will be important. I heard p3 instances have much better nvlink connections. So you should switch to those if training time is a concern.

On Apr 13, 2023, at 1:14 PM, fernando-deka ***@***.***> wrote:

﻿

Hey, thanks for your reply.

I am using the code from the ray official repository: https://github.com/ray-project/ray/tree/master/python/ray/air/examples/dreambooth
It seems that the code there is your code + some slight modifications to make it run across multiple instances, that is how I made it work.

I am running the script with the base model of runwayml/stable-diffusion-v1-5 and is only using 15/24 GRAM.
Why did you choose to use CompVis/stable-diffusion-v1-4 instead?

Actually performance does matter to me, I need to fine tune stable diffusion with 30k images of multiple different concepts and I need to scale this as much as possible, otherwise I am stuck with training times of over 2-3 weeks.

Thank you for your time!

**Comment by gjoliver** [comment]
fix for batch format is in. both here, and https://github.com/ray-project/ray/tree/master/python/ray/air/examples/dreambooth
